# Generated by Django 6.0.2 on 2026-02-19 13:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(help_text='Ej: CARDIO, PEDIA, DERMA', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la especialidad')),
                ('activa', models.BooleanField(default=True, help_text='Si está desactivada, no aparecerá en formularios')),
                ('icono', models.CharField(default='fa-user-md', help_text='Clase de Font Awesome (ej: fa-heart)', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en listados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE', 'Jefe de Médicos'), ('MEDICO', 'Médico'), ('ASISTENTE', 'Asistente')], default='ASISTENTE', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('costo_consulta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctores', to='core.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_ESPERA', 'En Sala de Espera'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.doctor')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones_generales', models.TextField(blank=True, help_text='Observaciones generales del expediente')),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas del paciente')),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Medicamentos que toma actualmente')),
                ('antecedentes', models.TextField(blank=True, help_text='Antecedentes médicos importantes')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente Médico',
                'verbose_name_plural': 'Expedientes Médicos',
                'permissions': [('can_view_expediente', 'Puede ver expedientes médicos'), ('can_edit_expediente', 'Puede editar expedientes médicos'), ('can_activate_expediente', 'Puede activar/desactivar expedientes')],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico_principal', models.CharField(help_text='Diagnóstico principal (CIE-10 recomendado)', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción detallada del diagnóstico')),
                ('tratamiento', models.TextField(help_text='Tratamiento prescrito')),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones para el paciente')),
                ('pronostico', models.TextField(blank=True, help_text='Pronóstico del cuadro clínico')),
                ('archivos_adjuntos', models.JSONField(blank=True, default=list, help_text="Lista de archivos adjuntos: [{'nombre': '', 'url': ''}]")),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(blank=True, help_text='Cita asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='core.cita')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_modificados', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Médico que realizó el diagnóstico', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_realizados', to='core.doctor')),
                ('expediente', models.ForeignKey(help_text='Expediente al que pertenece este diagnóstico', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='core.expediente')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-fecha'],
                'permissions': [('can_view_diagnostico', 'Puede ver diagnósticos'), ('can_edit_diagnostico', 'Puede editar diagnósticos')],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(blank=True, help_text='Cédula de Identidad (ej: V-12345678 o E-87654321)', max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='DD/MM/AAAA - La edad se calculará automáticamente', null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Alternativo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['ci'], name='core_pacien_ci_24e458_idx'), models.Index(fields=['activo'], name='core_pacien_activo_36aeeb_idx')],
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expediente', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.paciente'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['activo'], name='core_doctor_activo_e90507_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['especialidad'], name='core_doctor_especia_cb29fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('doctor', 'fecha', 'hora'), name='cita_unica_horario'),
        ),
    ]
