# Generated by Django 6.0.2 on 2026-02-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctor_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones_generales', models.TextField(blank=True, help_text='Observaciones generales del expediente')),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas del paciente')),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Medicamentos que toma actualmente')),
                ('antecedentes', models.TextField(blank=True, help_text='Antecedentes médicos importantes')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_modificados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expediente', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Expediente Médico',
                'verbose_name_plural': 'Expedientes Médicos',
                'permissions': [('can_view_expediente', 'Puede ver expedientes médicos'), ('can_edit_expediente', 'Puede editar expedientes médicos'), ('can_activate_expediente', 'Puede activar/desactivar expedientes')],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico_principal', models.CharField(help_text='Diagnóstico principal (CIE-10 recomendado)', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción detallada del diagnóstico')),
                ('tratamiento', models.TextField(help_text='Tratamiento prescrito')),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones para el paciente')),
                ('pronostico', models.TextField(blank=True, help_text='Pronóstico del cuadro clínico')),
                ('archivos_adjuntos', models.JSONField(blank=True, default=list, help_text="Lista de archivos adjuntos: [{'nombre': '', 'url': ''}]")),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(blank=True, help_text='Cita asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='core.cita')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_creados', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Médico que realizó el diagnóstico', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_realizados', to='core.doctor')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_modificados', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(help_text='Expediente al que pertenece este diagnóstico', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='core.expediente')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-fecha'],
                'permissions': [('can_view_diagnostico', 'Puede ver diagnósticos'), ('can_edit_diagnostico', 'Puede editar diagnósticos')],
            },
        ),
    ]
