# Generated by Django 6.0.2 on 2026-02-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expediente_diagnostico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='ci',
            field=models.CharField(blank=True, help_text='Cédula de Identidad (ej: V-12345678 o E-87654321)', max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='DD/MM/AAAA - La edad se calculará automáticamente', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_alternativo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Alternativo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['ci'], name='core_pacien_ci_24e458_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['activo'], name='core_pacien_activo_36aeeb_idx'),
        ),
    ]
